<?php

namespace ColorAnomaly\Quick\Domain;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-11 at 21:34:31.
 */
class QueueTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Queue
     */
    protected $q;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->q = new Queue();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testEnqDeq() {
        $this->assertEquals(1000, $this->q->enqueue());
        $this->assertEquals(1001, $this->q->enqueue());
        $this->assertEquals(1002, $this->q->enqueue());

        $this->assertEquals(1000, $this->q->dequeue());

        $this->assertEquals(1003, $this->q->enqueue());
    }

    public function testQueueOverflow() {
        $this->setExpectedException('ColorAnomaly\\Quick\\Domain\\QueueOverflowException');
        $this->q->setUpperBound(1003);
        
        $this->q->enqueue();
        $this->q->enqueue();
        $this->q->enqueue();
        
        $this->q->enqueue();
    }
    
    public function testQueueComplete() {
        $this->setExpectedException('ColorAnomaly\\Quick\\Domain\\QueueEmptyException');
        
        $this->q->enqueue();
        $this->q->enqueue();
        $this->q->enqueue();
        
        $this->q->dequeue();
        $this->q->dequeue();
        $this->q->dequeue();
        
        $this->q->dequeue();
    }

}
